[package]
edition = "2024"
name = "rnr"
version = "0.1.0"

[dependencies]
thiserror = "2.0.17"
indented = "0.1.0"
proc-macro2 = "1.0.70"
quote = "1.0.33"
regex = "1.10.2"
structopt = "0.3.26"
derive_more = { version = "2.1.0", features = ["constructor"] }
mips = { git = "https://vesuvio-git.neteq.ltu.se/pln/mips.git", features = [
  "env_log",
] }
clap = "4.5.53"

[dependencies.syn]
features = ["full", "extra-traits"]
version = "2.0.40"
