FROM rust:latest AS wasm-builder

RUN cargo install wasm-pack

WORKDIR /app
COPY . .

RUN wasm-pack build crates/wasm \
  --target web \
  --out-dir ../../playground/src/features/compiler/pkg

FROM node:22-alpine AS frontend-builder

WORKDIR /app/playground

COPY --from=wasm-builder /app/playground ./

RUN npm ci
RUN npm run build

FROM nginx:alpine

COPY --from=frontend-builder /app/playground/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
